In [ ]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized

In [ ]:
x = torch.empty(1) # scalar
print(x)

tensor([-1.2728e-16])


In [ ]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[-1.2727e-16,  3.0653e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00]])


In [ ]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[5.2383e-09, 3.0716e-41, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.5455, 0.1032, 0.2573],
        [0.6372, 0.4958, 0.3124],
        [0.1868, 0.7183, 0.9998],
        [0.9866, 0.7832, 0.3214],
        [0.9040, 0.6407, 0.0557]])


In [ ]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# check size
print(x.size())

torch.Size([5, 3])


In [ ]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [ ]:
# check type
print(x.dtype)

torch.float16


In [ ]:
[3.4.5]

In [ ]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [ ]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

In [ ]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [ ]:
# elementwise addition
#z = x + y
torch.add(x,y)

tensor([[0.6257, 1.0911],
        [0.2999, 1.0425]])

In [ ]:

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)


tensor([[1.1227, 0.5561],
        [1.3087, 1.1667]])

In [ ]:
# substraction
z = x - y
z = torch.sub(x, y)

In [ ]:
# multiplication
z = x * y
z = torch.mul(x,y)

In [ ]:
# division
z = x / y
z = torch.div(x,y)

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)


tensor([[0.9635, 0.4355, 0.3096],
        [0.6646, 0.4321, 0.4975],
        [0.1182, 0.1815, 0.9031],
        [0.7026, 0.0444, 0.5762],
        [0.2425, 0.1226, 0.4331]])


In [ ]:
print(x[:, 0])

tensor([0.9635, 0.6646, 0.1182, 0.7026, 0.2425])


In [ ]:
print(x[1, :])

tensor([0.6646, 0.4321, 0.4975])


In [ ]:
print(x[1,1])

tensor(0.4321)


In [ ]:

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.5163143873214722


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)

In [ ]:
y = x.view(16)
y

tensor([-0.3137,  0.0355, -0.5909,  0.7535,  0.3184,  0.3194,  0.4223,  0.5721,
         0.9153,  1.3459, -0.0317,  2.2633,  0.2952,  0.1072, -0.4903, -0.3094])

In [ ]:
z = x.view(-1, 8)
z

tensor([[-0.3137,  0.0355, -0.5909,  0.7535,  0.3184,  0.3194,  0.4223,  0.5721],
        [ 0.9153,  1.3459, -0.0317,  2.2633,  0.2952,  0.1072, -0.4903, -0.3094]])

In [ ]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:

# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
a.add_(1)


tensor([2., 2., 2., 2., 2.])

In [ ]:
print(b)

[2. 2. 2. 2. 2.]


In [ ]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:

# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)


In [ ]:
b = torch.from_numpy(a)
print(a)
print(b)

In [ ]:
# again be careful when modifying
a += 1
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y 
     

In [ ]:

# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

In [ ]:

# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()